# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test"
  lane :test do
    run_tests(scheme: "CIDemo")
  end

  desc "Build"
  lane :build do
    gym(scheme: "CIDemo",export_method:"development",clean:true,export_xcargs: "-allowProvisioningUpdates")
  end

  desc "Deploy"
  lane :deploy do
    sh "python fir.py -p ../CIDemo.ipa"
  end

end
